### ISSUE TITLE
Comments on this package so far, and suggestions for possible changes

### ISSUE THREAD

**Issue by gsrohde** [biocro/skelBML#10]
Comments on file **docs/README.md**:

> This repository contains a skeleton BioCro module library (skelBML), which is an R package representing a BioCro module library with a single example module.

It's confusing to describe the contents of `biocro/skelBML` as a BioCro module library or an R package since it only becomes such upon running the setup script.  Even after this is done, the package name likely won't be `skelBML`, unless perhaps the user chooses this name simply in order to create a minimal library so as to try things out.  So I think it would be better to describe this as framework for creating an R package.

> 3. Run the startup script

I think it's better to call this the "setup script."  (Similarly for the two other places where you refer to the "startup script.")

> Commit the changed files to your new repository. 

At this point, when the setup is run for the first time, there will be no _changed_ files, only _new_ ones.

> Rerun the startup script, as described above.

Slightly clearer possibly: "Rerun the startup [or setup] script, running it as described above" (since you didn't describe <em>re</em>running it).

---

I'm confused about the three "skeleton" files.  Perhaps this is because I first assumed, from the names, that these were _skeleton_ package DESCRIPTION, LICENCE, and NEWS files, in the same sense that skelBML is (or at least can be used to produce) a skeleton (i.e. _bare bones_) module library/R package.  But now I think you probably just mean that these are to be considered the _description_, _license_, and _news_ files for the skelBML repository.  Even so, I remain a little confused.

**DESCRIPTION_skeleton**

If I am understanding things correctly, there isn't and never will be an R package called "skelBML" with us as authors.  So it is confusing to me to have this file, that looks like an R package description file (except for the freeform license information text at the end) and that is named as if it is the basis for one.  It would be less confusing if this file were called something like "skelBML_respository_description".  Perhaps it's okay to keep the style of an R package description file, with a succession of lines of the form "FieldName: Value", but I think it might be less confusing if it were otherwise.  In any case, if you do keep to this style, I'd replace the first line with "Repository: biocro/skelBML"  Then, in the "Description" line, I'd say something like "Files and code for creating a basic BioCro module library ... ."

**LICENSE_skeleton.md**

Again, this would be better called `LICENSE_for_skelBML.md`, if that is in fact what it is.  Given that, except for a few whitespace differences, `LICENSE_skeleton` and `script/templates/LICENSE.md` are identical, it seems to me that perhaps the setup script should remove this file.  That `biocro/cgbml` (on the `update-from-skeleton` branch) has both `LICENSE.md` and `LICENSE_skeleton.md` (again, identical except for whitespace) is very confusing.

**NEWS_skeleton.md**

This also might be better called something like `skelBML_NEWS.md`.  And it also seems out of place in any derived package, so I think the setup script should remove it as well.

**Other comments:**

Would it make sense to add "Depends: R (>= 3.5.0)" to the DESCRIPTION template file?

**Comment by gsrohde** [comment]
One other potentially confusing thing:

The setup script writes the file `LICENSE.md` at the top level.  The `docs/README.md` file includes the instruction "If you wish to use a different license for distributing your package, you will need to modify LICENSE.md, DESCRIPTION, and README.md."

But the license file the setup script writes is simply a copy of version 2 of the GNU General Public License, and it includes the line "Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed."

So perhaps it would be less confusing if the README said something like this: "If you wish to use a different license for distributing your package, you will need to modify the DESCRIPTION and README.md files, and remove or replace LICENSE.md, as appropriate."

(But maybe I shouldn't worry about this any more than I should have worried about the rather awe-inspiring tag on my pillow that said "UNDER PENALTY OF LAW THIS TAG NOT TO BE REMOVED!" (in the olden days, before they added "EXCEPT BY THE CONSUMER").)

**Comment by eloch216** [comment]
> I'm confused about the three "skeleton" files. Perhaps this is because I first assumed, from the names, that these were _skeleton_ package DESCRIPTION, LICENCE, and NEWS files, in the same sense that skelBML is (or at least can be used to produce) a skeleton (i.e. _bare bones_) module library/R package. But now I think you probably just mean that these are to be considered the _description_, _license_, and _news_ files for the skelBML repository. 

Yes, I was intending for them to be the the _description_, _license_, and _news_ files for the skelBML repository. I can see why this would be confusing. I can rename them to add `skelBML` prefixes as suggested: `skelBML_dsecription`, `skelBML_license.md`, and `skelBML_news.md`. I think the prefix and different capitalization should help differentiate them from any description, license, or news files from a BioCro module library R package.

> If I am understanding things correctly, there isn't and never will be an R package called "skelBML" with us as authors. So it is confusing to me to have this file, that looks like an R package description file (except for the freeform license information text at the end) and that is named as if it is the basis for one. It would be less confusing if this file were called something like "skelBML_respository_description". Perhaps it's okay to keep the style of an R package description file, with a succession of lines of the form "FieldName: Value", but I think it might be less confusing if it were otherwise. In any case, if you do keep to this style, I'd replace the first line with "Repository: biocro/skelBML" Then, in the "Description" line, I'd say something like "Files and code for creating a basic BioCro module library ... ."

I will make some changes so the content of this file looks less like that of an R package description.

> **LICENSE_skeleton.md**
> 
> Again, this would be better called `LICENSE_for_skelBML.md`, if that is in fact what it is. Given that, except for a few whitespace differences, `LICENSE_skeleton` and `script/templates/LICENSE.md` are identical, it seems to me that perhaps the setup script should remove this file. That `biocro/cgbml` (on the `update-from-skeleton` branch) has both `LICENSE.md` and `LICENSE_skeleton.md` (again, identical except for whitespace) is very confusing.

I think that any BioCro module library R package derived from `skelBML` should retain a copy of the `skelBML` license, just as we retain a copy of the `boost` library license. People aren't always careful about this kind of thing, but I think we can provide a nudge in the right direction!

It's not necessarily the case that a derived package will use the same license, although the GNU GPL makes that very difficult in practice. I am wondering if maybe it would be better to license the skeleton library with the MIT or BSD licenses instead. (Same for the framework.) We talked about this before, but it's had some time to stew in my head and I've started to see the benefits of not using the GNU GPL, at least for the central parts of BioCro.

> **NEWS_skeleton.md**
> 
> This also might be better called something like `skelBML_NEWS.md`. And it also seems out of place in any derived package, so I think the setup script should remove it as well.

Yeah, this could probably be removed from derived packages. As long as the `skelBML` description file is retained, it should be clear which version of `skelBML` was used, and then the news file in the `skelBML` repository could be referenced.

> Would it make sense to add "Depends: R (>= 3.5.0)" to the DESCRIPTION template file?

I'm not sure. We added that requirement to `BioCro` because some of the `data` files were saved in a newer version of R, and they can't be opened with older versions below `3.5.0`. There's no data in a freshly-created module library, so that consideration doesn't apply. On the other hand, I guess it's unlikely that the code will work for _any_ version of R, and since it would be tedious to figure out the actual minimal version, we could just set it to 3.5.0. I guess that's your favored solution. There probably aren't too many potential BioCro users using older versions of R that they cannot upgrade, so I guess it wouldn't hurt to add that. If it causes a problem for someone, we could always change it as necessary.

**Comment by eloch216** [comment]
@gsrohde I've tried to address all the comments here in PR https://github.com/biocro/skelBML/pull/8.
